### ISSUE TITLE
Fix: CI Breaking Tests

### ISSUE THREAD

**Issue by techsavvyash** [ChakshuGautam/cQube-ingestion#102]
# Description

Currently, some tests have been commented out so that the CI passes, they need to fixed and replaced accordingly.

There are the locations of those tests: [first](https://github.com/ChakshuGautam/cQube-POCs/blob/jharkhand/impl/c-qube/src/services/csv-adapter/parser/event-grammar/event-grammar.service.spec.ts#L13), [second](https://github.com/ChakshuGautam/cQube-POCs/blob/jharkhand/impl/c-qube/src/services/csv-adapter/parser/utils/dateparser.spec.ts#L11)  and [third](https://github.com/ChakshuGautam/cQube-POCs/blob/jharkhand/impl/c-qube/src/services/csv-adapter/parser/utils/dateparser.spec.ts#L41)

The task is to figure out why are they failing in the Github CI and fix the issue.

Linked to #115

**Comment by shashwatm1111** [comment]
I'm working on this issue . Kindly assign me this .

**Comment by techsavvyash** [comment]
Hey @shashwatm1111,
Please go ahead and submit a PR.
Thanks

**Comment by tushar5526** [comment]
Hi @techsavvyash, second and third issues you mentioned formerly are not relevant because the underlying date parser logic is changed and is not in sync with the tests. I think we can remove these tests or re-write them for the new code.
