### ISSUE TITLE
Fix: Coveralls not updating test coverage in the README badge

### ISSUE THREAD

**Issue by techsavvyash** [ChakshuGautam/cQube-ingestion#109]
# Description

[Coveralls](https://coveralls.io) has been setup in the github actions, but right now it is not sending the correct test coverage data and hence the coverage is not being shown in the github badge accordingly.

## Goals

Coveralls badge in the `README` updated with proper test coverage statistics

## Project

cQube-ingestion

## Organisation Name
Samagra | Transforming Governance

## Mentor(s)
@techsavvyash @ChakshuGautam 

## Technical Skills Needed

GitHub Actions, Coveralls

## Complexity

Low

## Category

Bug fix

## Sub Category

CI/CD

## Domain

Others

**Comment by KDwevedi** [comment]
comment

**Comment by Lucif3r-in** [comment]
Hey @techsavvyash do we have a Coveralls account linked to this repository?

**Comment by techsavvyash** [comment]
Moved this to [codecov](https://about.codecov.io/) in my [fork](https://github.com/techsavvyash/cQube-ingestion) which updates test coverage correctly.
