### ISSUE TITLE
Broken CI file references

### ISSUE THREAD

**Issue by techsavvyash** [ChakshuGautam/cQube-ingestion#115]
# Description

In a very weird scenario the github actions CI is not picking up the correct file when referencing the `'./test/fixtures/ingestionConfigs/programs/test-complete-ingestion/testcompleteingestion-event.grammar.csv'` file and this causes a few of the tests to fail on the CI while they work perfectly well on the local dev environment, The cause and fix for this bug is needed to be figured out.

This is the file that gets referenced always: https://github.com/ChakshuGautam/cQube-POCs/blob/jharkhand/impl/c-qube/ingest/dimensions/school-dimension.grammar.csv

## Goals

GitHub Actions CI being able to find and read these files

## Product

cQube

## Project

cQube-ingestion

## Organisation Name
Samagra | Transforming Governance

## Mentor(s)
@techsavvyash @ChakshuGautam 

## Technical Skills Needed

NodeJS, GitHub Actions, DevOps (Novice)

## Complexity

Low

## Category

Bug fix

## Sub Category

CI/CD

## Domain

Others

**Comment by techsavvyash** [comment]
A probable fix for this could be setup a proper module inside of the spec.ts file, something like https://github.com/techsavvyash/cQube-POCs/blob/d12314fc591dc5efa49e367c20549b0c60399478/impl/c-qube/src/services/csv-adapter/csv-adapter.service.spec.ts#L57

**Comment by KDwevedi** [comment]
comment

**Comment by Deekshithrathod** [comment]
@techsavvyash Given the fact that I know nothing about TypeScript other than the fact that it's a superset of JS, would you recommend that I take this issue up? 
My thinking is that I can investigate the cause of this issue without having to understand the business logic stuff.

**Comment by techsavvyash** [comment]
TODO: 
1. List down files that need 100% coverage
2. fix coveralls badge
3. investigate and fix this ticket

**Comment by techsavvyash** [comment]
Hey @Deekshithrathod, 
please go ahead and investigate, i dont think this has anything to do with you knowing typescript. This is most probably because of broken file references either in the code bundler or some problem with file references in GHA. These are just guesses that I have the issue might be something else as well.

**Comment by techsavvyash** [comment]
fixed with #160
