### ISSUE TITLE
Make docker-compose.yml parametric with env variables.

### ISSUE THREAD

**Issue by ChakshuGautam** [ChakshuGautam/cQube-ingestion#67]
Currently the docker-compose.yaml exposes secrets for a DB. Remove that and move those to an env file.

**Comment by Midas847** [comment]
Hey , I made a PR for this issue #114

**Comment by Deekshithrathod** [comment]
@techsavvyash raised a PR for this, can you take a look at it?

**Comment by techsavvyash** [comment]
#140 fixes this
